#!/bin/bash
#build and upload for QA....
#
#make by zhuangxiaowei_dev@163.com
#
#hahahahahahahhahahaha

changeLog="$HOME/Desktop/changeLog.txt"
archivePath="$HOME/Desktop/AutoLearning_Archive"
archiveFile="ForQA.xcarchive"
ipaPath="$HOME/Desktop/AutoLearning_IPA"
ipaFile="ForQA.ipa"
projectPath="$HOME/iOSProjects/AutoLearning"
ipaExportOptionsPlist="$ipaPath/options.plist"
firToken="08ac5648ec2638bd11fc1e3e173951af"
appName="测试库版本"
scheme="ForQA"
conf="Debug"
altool="$HOME/"

if [ $1 -eq 1 ]
then
    echo "=================== 正式库安装包 ==================="
    archiveFile="ForQARelease.xcarchive"
    ipaFile="ForQARelease.ipa"
    appName="正式库版本"
    scheme="ForQARelease"
    conf="Release"
elif [ $1 -eq 2 ]
then
    echo "=================== 上传AppStore ==================="
    archiveFile="ForRelease.xcarchive"
    ipaFile="ForRelease.ipa"
    appName="路上读书"
    scheme="ForRelease"
    conf="Release"
else
    echo "=================== 测试库安装包 ===================="
fi

ipaArchiveFilePath="$archivePath/$archiveFile"
publicIpaPath="$ipaPath/$ipaFile"

if [ -e $changeLog ]
then
    rm -rf $changeLog
#else
#    touch $changeLog
#    echo "创建$changeLog文件"
fi

echo "输入本次发包修改的内容(输入'q'或'Q'结束):"
read inputData
while [ "$inputData"x != "q"x -a "$inputData"x != "Q"x ] 
do
    emailData="$emailData$inputData<br>"
    echo $inputData >> $changeLog
    read inputData
done

if [ -z "$emailData" ]
then 
    echo "修改内容不能为空"
    exit 1
fi

#删除上次打包生成的文件
rm -rf $publicIpaPath
rm -rf $ipaArchiveFilePath

#获取更新日志
#cd ~/Desktop
#data=""
#logFile="changeLog.txt"
#if [ -s "${logFile}" ]
#then
#    for line in `cat ${logFile}`
#    do
#        data="$data$line<br>"
#    done
#    echo $data
#    if [ -z "$data" ]
#    then
#        echo "输入修改内容"
#        exit 1
#    fi
#else
#    echo "没有找到${logFile} 文件" 
#    exit 1
#fi

#打包并上传
cd $projectPath 
echo "清理项目中......"
xcodebuild clean -quiet
echo "Archiving......"
xcodebuild -workspace AutoLearning.xcworkspace -scheme $scheme -configuration $conf -archivePath $ipaArchiveFilePath archive -quiet
cd $archivePath 
if [ -e "$archiveFile" ]
then
    cd $projectPath
    echo "导出ipa包......"
    xcodebuild -exportArchive -archivePath $ipaArchiveFilePath -exportOptionsPlist $ipaExportOptionsPlist -exportPath $ipaPath -quiet

    cd $ipaPath
    if [ -e "$ipaFile" ]
    then
        if [ $1 -eq 2 ]
        then
            echo "==================== 开始上传AppStore ==================="
            cd /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Versions/A/Support
            #验证 
            #./altool --validate -f $publicIpaPath -u 314122537@qq.com -p bwcm-qypv-iryo-ddhb --output-format xml
            #上传
            ./altool --upload-app -f $publicIpaPath -u 314122537@qq.com -p bwcm-qypv-iryo-ddhb --output-format xml
        else 
            echo "上传fir平台中......"
            fir publish $publicIpaPath -T $firToken --changelog="$changeLog"
        fi 
        #更改版本号
        cd $projectPath
        echo "修改build号......"
        xcrun agvtool next-version -all
        #获取打包完成后的包名,然后向测试人员发送邮件
        cd ~/Tools
        echo "向相关人员发送邮件......"
        python vemail.py $appName $emailData
        echo "=====================打包完成==================="
    else
        echo "=====================打包打败==================="
    fi
else
    echo "打包失败"
fi

