#!/bin/bash

tmpDirectory="/work/tmp/"
resignProvisionFile="/work/ResignAppFiles/iRegign.mobileprovision"
payloadPath="${tmpDirectory}Payload"
entitleFilePath="/work/ResignAppFiles/entitlements.plist"
plistBuddy="/usr/libexec/PlistBuddy"
originFile="$1"
resignedFile="${originFile%.*}-resigned.ipa"
certificationName="iPhone Distribution: HA Youmi INC"

if [ -f "$resignedFile" ]; then
    echo "find old resigned file, will delete it!"
    rm -rf "$resignedFile"
fi

if [ -d $tmpDirectory ]; then 
    echo "find tmp directory, will delete it!"
    rm -rf $tmpDirectory
fi

if [ -d $payloadPath ]; then
    echo "Payload directory is exists, delete it!"
    rm -rf $payloadPath
fi

#解压ipa包, 生成Payload文件夹
unzip -qo "$1" -d $tmpDirectory

appPath=`ls $payloadPath`
resignAppPath="${payloadPath}/${appPath}"
#Info.plist文件路径
infoPath="${resignAppPath}/Info.plist"
codeSignaturePath="${resignAppPath}/_CodeSignature"
#删除_CodeSignature文件夹
rm -rf $codeSignaturePath

embeddedProvisionFile="${resignAppPath}/embedded.mobileprovision"

#替换embedded.mobileprovision
cp "$resignProvisionFile" "$embeddedProvisionFile"

#**********************需要修改application-identifier为新的BundleId**************#
fullEntitlesFile="${tmpDirectory}entitlements_full.plist"
targetEntitleFile="${tmpDirectory}entitlements.plist"

security cms -D -i "$embeddedProvisionFile" > $fullEntitlesFile
$plistBuddy -x -c 'Print:Entitlements' $fullEntitlesFile > $targetEntitleFile

fileName=${appPath%.*}

#************************8拼接新的BundleId, 用在entitlements.plist文件中********************#
###注意:(花一整天总结出来的血泪教训)
###如果同一个包打包时, 前一次application-identifier设置的是通配符(*), 那后一次这里设置了application-identifier的话, 安装会失败!!!!
###反之亦然
#获取要重打包应用的BundleId
bundleId=$($plistBuddy -c "Print :CFBundleIdentifier" "$infoPath")
teamId=$($plistBuddy -c "Print :com.apple.developer.team-identifier" "$targetEntitleFile")
targetBundleId="$teamId.$bundleId"
$plistBuddy -c "Set :application-identifier $targetBundleId" "$targetEntitleFile"
$plistBuddy -c "Delete :com.apple.developer.team-identifier" "$targetEntitleFile"
$plistBuddy -c "Delete :keychain-access-groups" "$targetEntitleFile"

find -d "$tmpDirectory"  \( -name "*.app" -o -name "*.appex" -o -name "*.framework" -o -name "*.dylib" \) > "${tmpDirectory}needCodeSigns.txt"

while IFS='' read -r line || [[ -n "$line" ]]; do
    codesign --continue -f -s "$certificationName" --entitlements="$targetEntitleFile" "$line"
done < "${tmpDirectory}needCodeSigns.txt"

#压缩Payload并改后缀为ipa
cd "$tmpDirectory"
zip -qry ab.ipa "Payload"
mv ab.ipa "$resignedFile"

### 这下面这行代码打包出来的怎么就不能安装了!!!!!!!
### (花一个下午终于发现)下面这行代码不能打包成功, 是因为会把Payload上一整个路径打包进去!!!! $payloadPath是/work/tmp/Payload 打包完成再解压不是Payload文件夹, 是/work/tmp/Payload!!!!!!!
# zip -qry "$resignedFile" "$payloadPath"

echo "output file: $resignedFile"
#扫尾
rm -rf $tmpDirectory