#!/bin/bash
# cd ~/Desktop/ReadyForQA
# rm -rf *
appName=""
for i in $(ls -l ~/Desktop/ReadyForQA |awk '/^d/{print $NF}')
do 
  appName=$(basename $i .app.dSYM)
done
echo $appName
# python vemail.py $appName
# cd ~/iOSProjects/AutoLearning
# xcrun agvtool next-version -all
